name: Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Await Cloudflare Pages build and send Slack notification
        uses: arddluma/cloudflare-pages-slack-notification@v2.5
        with:
          accountEmail: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
          apiKey: ${{ secrets.CLOUDFLARE_API_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          project: uplink-docs
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          slackWebHook: ${{ secrets.SLACK_WEBHOOK_URL }}
